export * from "./modals/modals-page";
export * from "./dashboard/dashboard-page";
export * from "./calendar/calendar-page";
export * from "./charts/charts-page";
export * from "./table/table-page";
export * from "./form/form-page";
export * from "./error-pages/404-page";
export * from "./error-pages/500-page";
export * from "./login/login-page";
